# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Generate static page
      run: |
        ls -la
        docker run -v $GITHUB_WORKSPACE:/build_dir jeanphix/ghost.py:2.0.0-dev python3 ./ghost_script.py
        cat hacktivity
        
    - name: Check for new reports
      run: |
        pip install wheel
        pip install bs4
        python hackerone.py